GetMesh("TEXT", 0, "Image//TEXT.tga")
GetMesh("TOWER", 0, "Image//TOWER.tga")
GetMesh("TOWER_MID", 0, "Image//TOWER.tga")
GetMesh("TOWER_LOW", 0, "Image//TOWER.tga")
GetMesh("CRATE", 0, "Image//CRATE.tga")
GetMesh("CRATE_MID", 0, "Image//ORANGE.tga")
GetMesh("CRATE_LOW", 0, "Image//GREEN.tga")
GetMesh("BUILDING_1", 0, "Image//BUILDING_1.tga")
GetMesh("BUILDING_1_MID", 0, "Image//ORANGE.tga")
GetMesh("BUILDING_1_LOW", 0, "Image//GREEN.tga")
GetMesh("WALL", 0, "Image//WALL.tga")
GetMesh("WALL_MID", 0, "Image//ORANGE.tga")
GetMesh("WALL_LOW", 0, "Image//GREEN.tga")
GetMesh("SKYPLANE", 0, "Image//SKYPLANE.tga")
GetMesh("COMGROUND", 0, "Image//WORLD//W_GRASS.tga")
GetMesh("COMGROUND", 1, "Image//WORLD//W_SNOW.tga")
GetMesh("QUAD", 0, "Image//calibri.tga");
GetMesh("MONK_HEAD", 0, "Image//MONK//bad tang_diffuse.tga")
GetMesh("MONK_HEAD_MID", 0, "Image//MONK//bad tang_roughness.tga")
GetMesh("MONK_HEAD_LOW", 0, "Image//MONK//bad tang_ao.tga")
GetMesh("MONK_BODY", 0, "Image//MONK//bad tang_diffuse.tga")
GetMesh("MONK_BODY_MID", 0, "Image//MONK//bad tang_roughness.tga")
GetMesh("MONK_BODY_LOW", 0, "Image//MONK//bad tang_ao.tga")
GetMesh("MONK_LEFT_ARM", 0, "Image//MONK//bad tang_diffuse.tga")
GetMesh("MONK_LEFT_ARM_MID", 0, "Image//MONK//bad tang_roughness.tga")
GetMesh("MONK_LEFT_ARM_LOW", 0, "Image//MONK//bad tang_ao.tga")
GetMesh("MONK_RIGHT_ARM", 0, "Image//MONK//bad tang_diffuse.tga")
GetMesh("MONK_RIGHT_ARM_MID", 0, "Image//MONK//bad tang_roughness.tga")
GetMesh("MONK_RIGHT_ARM_LOW", 0, "Image//MONK//bad tang_ao.tga")
GetMesh("MONK_LEFT_LEG", 0, "Image//MONK//bad tang_diffuse.tga")
GetMesh("MONK_RIGHT_LEG", 0, "Image//MONK//bad tang_diffuse.tga")
